# Generated by Django 3.2.4 on 2021-08-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=300)),
                ('institution', models.CharField(max_length=300)),
                ('time_from', models.IntegerField()),
                ('time_to', models.IntegerField()),
            ],
            options={
                'ordering': ('-time_from',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='portfolio')),
                ('demo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('job', models.CharField(max_length=300)),
                ('home_desc', models.CharField(max_length=300)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=300)),
                ('aboutme', models.CharField(max_length=300)),
                ('experience', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('companies', models.IntegerField()),
                ('cv', models.FileField(upload_to='files')),
                ('blobimg', models.ImageField(upload_to='self')),
                ('aboutimg', models.ImageField(upload_to='self')),
                ('projectimg', models.ImageField(upload_to='self')),
                ('discount', models.IntegerField()),
                ('colortheme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('time', models.IntegerField()),
                ('icon', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.URLField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('star', models.FloatField()),
                ('saying', models.TextField()),
                ('img', models.ImageField(upload_to='testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('time_from', models.IntegerField()),
                ('time_to', models.IntegerField()),
            ],
            options={
                'ordering': ('-time_from',),
            },
        ),
        migrations.CreateModel(
            name='Subskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('percentage', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentskill', to='main.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=300)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentservice', to='main.service')),
            ],
        ),
    ]
