# Generated by Django 3.2.4 on 2021-08-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sociallink_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='label',
            field=models.CharField(default='t', max_length=1),
        ),
    ]
