# Generated by Django 3.2.4 on 2021-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sociallink_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subskill',
            name='percentage',
            field=models.CharField(default='p__', max_length=6),
        ),
    ]
