# Generated by Django 3.2.4 on 2021-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='star2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='star3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='star',
            field=models.IntegerField(default=1),
        ),
    ]
